name: lokix
services:
  crawler:
    build:
      # context is either a path to a directory containing a Dockerfile, or a url to a git repository. 
      # When the value supplied is a relative path, it is interpreted as relative to the location of the Compose file.
      context: .
      dockerfile: Dockerfile
      target: build-release-stage
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      MONGO_URI: "mongodb://crawler:crawler-pwd@db:27017"
  db:
    image: mongo
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping").ok'
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: crawler-pwd
    volumes:
      - crawler-volume:/data/db

volumes:
  crawler-volume: