name: lokix
services:
  crawler:
    build:
      # context is either a path to a directory containing a Dockerfile, or a url to a git repository. 
      # When the value supplied is a relative path, it is interpreted as relative to the location of the Compose file.
      context: .
      dockerfile: Dockerfile
      target: build-release-stage
  
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: crawler-pwd
    volumes:
      - crawler-volume:/data/db
volumes:
  crawler-volume: