name: lokix
services:
  # Spin up the db first then the crawler
  # I had a healthcheck + depends on before, but the health checks made it very difficult to track the logs of the crawler
  # So I removed them (the compose-test.yml employs this though)
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: crawler-pwd
    volumes:
      - crawler-volume:/data/db

  crawler:
    build:
      # context is either a path to a directory containing a Dockerfile, or a url to a git repository. 
      # When the value supplied is a relative path, it is interpreted as relative to the location of the Compose file.
      context: .
      dockerfile: Dockerfile
      target: build-release-stage
    environment:
      MONGO_URI: "mongodb://crawler:crawler-pwd@db:27017"

volumes:
  crawler-volume: